pipeline {
  agent {
    docker {
      image 'node:6-alpine'
      args '-u root -p 3000:3000'
    }
  }
  
  stages {
        stage('Preparation') { // for display purposes
        // Get some code from a GitHub repository
        steps {
             git 'https://github.com/neelaruban/creating-a-pipeline-in-blue-ocean.git'
        }
        }
       stage('Build') {
       steps {
        sh 'npm install'
       }
     }
         stage('Test') {
      environment {
        CI = 'true'
      }
      steps {
        sh './jenkins/scripts/test.sh'
      }
    }
    stage('Deliver') {
      steps {
        sh './jenkins/scripts/deliver.sh'
        input 'Finished using the web site? (Click "Proceed" to continue)'
        sh './jenkins/scripts/kill.sh'
      }
    }
  }
}